### ISSUE TITLE
test.cpp have problems.

### ISSUE THREAD

**Issue by peterGuang** [seomoz/simhash-cpp#2]
when I did make, I got this.
Help help~

test.cpp:158:70: error: no match for call to ‘(Simhash::Simhash<>) (const char*, std::basic_string<char>::size_type)’
hash.hpp:26:11: note: candidate is:
hash.hpp:39:16: note: Simhash::hash_t Simhash::Simhash<Hash>::operator()(char**) [with Hash = Simhash::jenkins, Simhash::hash_t = long unsigned int]
hash.hpp:39:16: note:   candidate expects 1 argument, 2 provided
test.cpp:161:70: error: no match for call to ‘(Simhash::Simhash<>) (const char*, std::basic_string<char>::size_type)’
hash.hpp:26:11: note: candidate is:
hash.hpp:39:16: note: Simhash::hash_t Simhash::Simhash<Hash>::operator()(char**) [with Hash = Simhash::jenkins, Simhash::hash_t = long unsigned int]
hash.hpp:39:16: note:   candidate expects 1 argument, 2 provided
test.cpp:175:47: error: no match for call to ‘(Simhash::Simhash<>) (const char*, std::basic_string<char>::size_type)’
hash.hpp:26:11: note: candidate is:
hash.hpp:39:16: note: Simhash::hash_t Simhash::Simhash<Hash>::operator()(char**) [with Hash = Simhash::jenkins, Simhash::hash_t = long unsigned int]
hash.hpp:39:16: note:   candidate expects 1 argument, 2 provided
make: *** [test] Error 1

**Comment by dlecocq** [comment]
Related to #9

**Comment by b4hand** [comment]
The compilation errors should be resolved now.

**Comment by skywindy** [comment]
how can i build it on windows?
when i build it on windows with gcc,I use the commend make,it come across an error?

  正在创建库 build\temp.win-amd64-3.5\Release\simhash/simhash-cpp/src\simhash.cp35-win_amd64.lib 和对象 build\temp.win-amd64-3.5\Release\simhash/simhash-cpp/src\simhash.cp35-win_amd64.exp
正在生成代码
已完成代码的生成
nosetests --verbose --nocapture
process_begin: CreateProcess(NULL, nosetests --verbose --nocapture, ...) failed.
make (e=2):
makefile:11: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by b4hand** [comment]
@skywindy: You're commenting on a very old and unrelated, closed issue, so you're unlikely to find help asking here.

Also, keep in mind that no effort for supporting Windows compilation has been made to this point. In general, you can't just compile something on a different platform and expect it to work. I can't tell what's gone wrong in the error message that you gave. It's possible there's information in the Chinese text that I can't read, but it's unlikely that I'll be able to help you without you doing much of the heavy lifting. I don't have access to a Windows computer to do any test compilation myself, and if you're unfamiliar with porting code to a new platform, it's unlikely that you'll succeed without specific knowledge of both Windows and Linux compilation.
