### ISSUE TITLE
Implement method that returns all similar hashes

### ISSUE THREAD

**Issue by gosom** [seomoz/simhash-cpp#38]
Hi,

Currently in the master branch there is a find_all method that returns all pair of matches.

Would be nice if there was a method that given a t_hash it returns all the similar ones to the t_hash

something like:

find(hashes, t_hash) -> returns a vector of all the similar hashes with t_hash

**Comment by dlecocq** [comment]
We'd like to implement such a function. In fact, previous versions did have such a function: https://github.com/seomoz/simhash-cpp/blob/v0.1.0/src/simhash.h#L208

That version depended on `libJudy`, which has issues when running on 14.04+, so we've temporarily dropped it. At some point we'll add similar functionality back in when we find / choose an appropriate prefix trie implementation.

**Comment by gosom** [comment]
I am already using that version, but also would like to remove libjudy dependency.

thanks for the reply
